com.caching.geode_1:
  gemfire:
    locator:
      host: localhost
      port: 10334
    dataModelPackage: com.caching.geode_1.model.*

server:
  port: 8088

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false